# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VexELO_rankings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_num',
            field=models.IntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
    ]
